name: deployment
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: echo "Deploying..."

  
